name: Export Unity Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Unity 라이선스 활성화
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # Unity 패키지 내보내기
      - name: Export Unity Package
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: '2023.1.0f1'
          customParameters: -executeMethod ExportPackageExample.Editor.UnityPackageExporter.Export

      # 아티팩트 업로드
      - name: Upload Unity Package
        uses: actions/upload-artifact@v3
        with:
          name: MyUnityPackage
          path: Build/MyUnityPackage.unitypackage
